# Generated by Django 3.2.6 on 2021-12-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_persona'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
